
#################################################
# The scope of this Dockerfile is the folder of 
# the CP challenge.
#################################################

ARG BASE_IMAGE=
FROM ${BASE_IMAGE} 

ARG ISOLATED=
RUN test -z "${ISOLATED}" || echo "deb [trusted=yes arch=amd64] http://apt-mirror-$(grep DISTRIB_RELEASE= /etc/lsb-release | cut -d= -f2 | sed 's/\./-/g'):$(grep DISTRIB_RELEASE= /etc/lsb-release | cut -d= -f2 | sed 's/\.//g') $(grep DISTRIB_CODENAME /etc/lsb-release | cut -d= -f2) main universe" > /etc/apt/sources.list
RUN apt-get update && apt-get install -y \
	binutils-dev \
	bison \
	clang \
	file \
	flex \
	libaudit-dev \
	libbabeltrace-dev \
	libcap-dev \
	libcapstone-dev \
	libdw-dev \
	libelf-dev \
	libiberty-dev \
	liblzma-dev \
	libnuma-dev \
	libperl-dev \
	libpfm4-dev \
	libslang2-dev \
	libssl-dev \
	libtraceevent-dev \
	libunwind-dev \
	libzstd-dev \
	make \
	pkg-config \
	python3-dev \
	python3-pip \
	python3-setuptools \
	python3-yaml \
	rsync \
	systemtap-sdt-dev

COPY ./shellphish /shellphish

# Install perf
RUN cd /shellphish && tar -xf linux-6.10-rc5.tar.gz && mv linux-6.10-rc5 linux
RUN cd /shellphish/linux/tools/perf && make -j$NPROC_VAL && make install && chmod +x /shellphish/linux/tools/perf/perf
RUN /shellphish/linux/tools/perf/perf --version

