{
 "title": "CRS Dashboard",
 "description": "Main Dashboard for the Artiphishell CRS",
 "time": { "from": "2024-11-30T09:07:48.170Z", "to": "2024-11-30T13:08:07.228Z" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   { "name": "inter", "label": "Sampling", "query": "10s,30s,1m,2m,5m,10m,30m,1h" },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n  |> filter(fn: (r) => r._measurement == \"system\" and exists r.host)\r\n  |> keep(columns: [\"host\"])\r\n  |> distinct(column: \"host\")"
    }
   },
   {
    "name": "mountpoint",
    "label": "Mountpoint",
    "query": {
     "query": "import \"influxdata/influxdb/v1\"\r\n\r\nv1.tagValues(\r\n  bucket: \"${bucket}\",\r\n  tag: \"path\",\r\n  predicate: (r) => r._measurement == \"disk\" and r.host =~ /${server}/,\r\n  start: ${__from:date},\r\n  stop: ${__to:date}\r\n)\r\n"
    }
   },
   {
    "name": "cpu",
    "label": "CPU",
    "query": {
     "query": "import \"influxdata/influxdb/v1\"\r\n\r\nv1.tagValues(\r\n  bucket: \"${bucket}\",\r\n  tag: \"cpu\",\r\n  predicate: (r) => r._measurement == \"cpu\" and r.host =~ /${server}/,\r\n  start: ${__from:date},\r\n  stop: ${__to:date}\r\n)\r\n"
    }
   },
   {
    "name": "disk",
    "label": "Disk",
    "query": {
     "query": "import \"influxdata/influxdb/v1\"\r\n\r\nv1.tagValues(\r\n  bucket: \"${bucket}\",\r\n  tag: \"device\",\r\n  predicate: (r) => r._measurement == \"disk\" and r.host =~ /${server}/,\r\n  start: ${__from:date},\r\n  stop: ${__to:date}\r\n)\r\n"
    }
   },
   { "name": "bucket", "label": "bucket", "query": "artiphishell" },
   {
    "name": "container",
    "label": "container",
    "query": {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n  |> filter(fn: (r) => r._measurement == \"docker_log\" and exists r.container_name)\r\n    |> group()\r\n    |> keep(columns: [\"container_name\"])\r\n    |> unique(column: \"container_name\")"
    }
   },
   {
    "name": "start_time",
    "query": {
     "query": "import \"math\"\r\n\r\nfrom(bucket: \"artiphishell\")\r\n  |> range(start: 0) // Start at the earliest possible time\r\n  |> filter(fn: (r) => r._measurement == \"component_event\") // Replace with your measurement name\r\n  |> sort(columns: [\"_time\"], desc: false) // Ensure ascending order by time\r\n  |> first()\r\n  |> map(fn: (r) => ({\r\n    _time: r._time,\r\n    _value: int(v: r._time) / 1000000\r\n  }))\r\n  |> sort(columns: [\"_time\"], desc: false) // Ensure ascending order by time\r\n  |> first()"
    }
   },
   {
    "name": "end_time",
    "query": {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: 0) // Start at the earliest possible time\r\n  |> filter(fn: (r) => r._measurement == \"component_event\") // Replace with your measurement name\r\n  |> sort(columns: [\"_time\"], desc: false) // Ensure ascending order by time\r\n  |> last()\r\n  |> map(fn: (r) => ({\r\n    _time: r._time,\r\n    _value: int(v: r._time) / 1000000 \r\n  }))\r\n  |> sort(columns: [\"_time\"], desc: false) // Ensure ascending order by time\r\n  |> last()"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Runtime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "import \"math\"\r\n\r\nfirst_entry = from(bucket: \"${bucket}\")\r\n  |> range(start: 0) // Start at the earliest possible time\r\n  |> filter(fn: (r) => r._measurement == \"component_event\") // Replace with your measurement name\r\n  |> sort(columns: [\"_time\"], desc: false) // Ensure ascending order by time\r\n  |> first()\r\n  |> map(fn: (r) => ({\r\n    _time: r._time,\r\n    _value: r._time\r\n  }))\r\n  |> sort(columns: [\"_time\"], desc: false) // Ensure ascending order by time\r\n  |> first()\r\n\r\nlast_entry = from(bucket: \"${bucket}\")\r\n  |> range(start: 0) // Start at the earliest possible time\r\n  |> filter(fn: (r) => r._measurement == \"component_event\") // Replace with your measurement name\r\n  |> sort(columns: [\"_time\"], desc: false) // Ensure ascending order by time\r\n  |> last()\r\n  |> map(fn: (r) => ({\r\n    _time: r._time,\r\n    _value: r._time\r\n  }))\r\n  |> sort(columns: [\"_time\"], desc: false) // Ensure ascending order by time\r\n  |> last()\r\n\r\nunion(tables: [last_entry, first_entry])  \r\n  |> map(fn: (r) => ({\r\n    _time: r._time,\r\n    _value: uint(v: r._time) // Convert _time to integer (nanoseconds)\r\n  }))\r\n  |> difference(columns: [\"_value\"]) // Subtract first from last\r\n  |> map(fn: (r) => ({r with _value: math.abs(x: float(v: r._value))}))\r\n",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n  |> filter(fn: (r) => r._measurement == \"system\" and r._field == \"n_cpus\" and r.host =~ /$server$/)\r\n  |> last()\r\n",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* -1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "Processes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n  |> filter(fn: (r) => r._measurement == \"processes\" and r._field == \"total\" and r.host =~ /$server$/)\r\n  |> aggregateWindow(every: ${inter}, fn: max, column: \"_value\", createEmpty: false)",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* -1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n  |> filter(fn: (r) => r._measurement == \"processes\" and r._field == \"total_threads\" and r.host =~ /$server$/)\r\n  |> aggregateWindow(every: ${inter}, fn: max)\r\n",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* -1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n  |> filter(fn: (r) => r._measurement == \"cpu\" and r._field == \"usage_idle\" and r.cpu == \"cpu-total\" and r.host =~ /$server$/)\r\n  |> aggregateWindow(every: ${inter}, fn: mean, createEmpty: false)\r\n  |> last()\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      usage: 100.0 - r._value\r\n  }))\r\n",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* -1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "from(bucket: \"artiphishell\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n  |> filter(fn: (r) => r._measurement == \"mem\" and r._field == \"used_percent\" and r.host =~ /$server$/)\r\n  |> aggregateWindow(every: ${inter}, fn: mean, createEmpty: false)\r\n  |> last()\r\n",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Swap usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swap",
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n  |> filter(fn: (r) => r._measurement == \"swap\" and r._field == \"used_percent\" and r.host =~ /$server$/)\r\n  |> aggregateWindow(every: ${inter}, fn: mean, createEmpty: false)\r\n",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "RootFS Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swap",
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})  // Use a wide range to ensure the latest value is captured\r\n  |> filter(fn: (r) => r._measurement == \"disk\" and r._field == \"used_percent\" and r.path == \"/\")\r\n  |> group(columns: [\"host\", \"path\"])  // Group by host and path to ensure granularity\r\n  |> last()\r\n  |> keep(columns: [\"_time\", \"host\", \"path\", \"_value\"])\r\n  |> rename(columns: {_value: \"latest_used\"})",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n  |> filter(fn: (r) => r._measurement == \"docker\" and r._field == \"n_containers_running\" and r.host =~ /$server$/)\r\n  |> aggregateWindow(every: ${inter}, fn: max, column: \"_value\", createEmpty: false)",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* -1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  { "title": "CRS STATS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Component Lifetimes",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "query": "import \"experimental\"\r\nimport \"strings\"\r\nimport \"dict\"\r\n\r\nall_component_status = from(bucket: \"${bucket}\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n  |> filter(fn: (r) => r._measurement == \"component_event\")\r\n\r\nfinal_event = all_component_status\r\n  |> keep(columns: [\"_time\"])\r\n  |> sort(columns: [\"_time\"])\r\n  |> rename(columns: {\"_time\": \"_value\"})\r\n  |> last()\r\n  |> findRecord(fn: (key) => true, idx: 0)\r\n\r\nhostname_dict = all_component_status\r\n  |> keep(columns: [\"hostname\", \"component_name\"])\r\n  |> distinct(column: \"hostname\")\r\n  |> drop(columns: [\"_value\"])\r\n\r\ncomponent_times = all_component_status\r\n  |> filter(fn: (r) => r._field == \"START\" or r._field == \"FINISH\")\r\n  |> keep(columns: [\"_field\", \"_time\", \"hostname\", \"_value\", \"component_name\"])  \r\n  |> group(columns: [\"hostname\"])\r\n  |> reduce(fn: (r, accumulator) => ({\r\n    start: if r._field == \"START\" and (r._time < accumulator.start or accumulator.start == time(v: 0))  then r._time else accumulator.start,\r\n    stop: if r._field == \"FINISH\" and (r._time > accumulator.stop or accumulator.stop == final_event._value) then r._time else accumulator.stop,\r\n    hostname: r.hostname,\r\n    component_name: r.component_name\r\n    }), identity: {start: time(v: 0), stop: final_event._value, hostname: \"\", component_name: \"\"})\r\n  |> group()\r\n\r\ncomponent_times\r\n  |> group(columns: [\"component_name\"])\r\n  |> rename(columns: {\"hostname\": \"\"})"
    }
   ]
  },
  {
   "title": "Running Instances",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "import \"experimental\"\r\n\r\nfrom(bucket: \"${bucket}\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n  |> filter(fn: (r) => r._measurement == \"component_event\" and r.component_name == \"AFL++\")\r\n  |> keep(columns: [\"_time\", \"replica_id\", \"component_id\"])\r\n  |> map(fn: (r) => ({ r with replica_id: int(v: r.replica_id) }))\r\n  |> group(columns: [\"component_id\"])\r\n  |> aggregateWindow(every: 1m, fn: max, column: \"replica_id\", createEmpty: false)\r\n  |> group(columns: [\"_time\"])\r\n  |> sum(column: \"replica_id\")\r\n  |> group()\r\n  |> rename(columns: {\"replica_id\": \"AFL++\"})"
    },
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: ${__from:date}, stop: ${__to:date})\n  |> filter(fn: (r) => r._measurement == \"component_event\" and r.component_name != \"AFL++\" and (r._field == \"START\" or r._field == \"FINISH\"))\n  |> keep(columns: [\"_time\", \"component_name\", \"_value\"])\n  |> aggregateWindow(every: ${inter}, fn: sum, createEmpty: false)\n  |> cumulativeSum()"
    }
   ]
  },
  {
   "title": "${container} Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 18 },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: \"${bucket}\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n  |> filter(fn: (r) => r._measurement == \"docker_log\" and r._field == \"message\" and r.container_name == \"${container}\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> sort(columns: [\"_time\"])\r\n  |> reduce(fn: (r, accumulator) => ({\r\n    _time: r._time,\r\n    _value: strings.joinStr(arr: [accumulator._value, r._value], v: \"\\n\")// \r\n  }), identity: {\r\n    _time: time(v: 0),\r\n    _value: \"\"\r\n  })"
    }
   ]
  },
  {
   "title": "LLM Cost",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 11, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "query": "component_costs = from(bucket: \"${bucket}\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n  |> filter(fn: (r) => r._measurement == \"component_event\" and r._field == \"LLM COST\")\r\n  |> keep(columns: [\"_time\", \"_value\", \"component_name\", \"component_id\"])\r\n  |> group(columns: [\"component_name\", \"component_id\"]) // Group by component_name for per-component cumulative sum\r\n  |> aggregateWindow(every: ${inter}, fn: sum)\r\n  |> cumulativeSum() // Calculate cumulative cost per component\r\n  |> drop(columns: [\"_start\", \"_stop\"])\r\n\r\n\r\nsummed = component_costs\r\n  |> group(columns: [\"_time\"])\r\n  |> sum()\r\n  |> group()\r\n  |> map(fn: (r) => ({\r\n    r with\r\n    component_name: \"Total\"\r\n  }))\r\n\r\n\r\npatchery_cost = component_costs\r\n  |> filter(fn: (r) => r.component_name == \"PatcherY\")\r\n  |> group(columns: [\"_time\"])\r\n  |> sum()\r\n  |> group()\r\n  |> map(fn: (r) => ({\r\n    r with\r\n    component_name: \"PatcherY Total\"\r\n  }))\r\n\r\npatcherq_cost = component_costs\r\n  |> filter(fn: (r) => r.component_name == \"PatcherQ\")\r\n  |> group(columns: [\"_time\"])\r\n  |> sum()\r\n  |> group()\r\n  |> map(fn: (r) => ({\r\n    r with\r\n    component_name: \"PatcherQ Total\"\r\n  }))\r\n\r\ngrammar_guy_cost = component_costs\r\n  |> filter(fn: (r) => r.component_name == \"Grammar Guy\")\r\n  |> group(columns: [\"_time\"])\r\n  |> sum()\r\n  |> group()\r\n  |> map(fn: (r) => ({\r\n    r with\r\n    component_name: \"Grammar Guy Total\"\r\n  }))\r\n\r\nunion(tables: [component_costs,patchery_cost,grammar_guy_cost,patcherq_cost,summed])\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"component_name\"], valueColumn: \"_value\")"
    }
   ]
  },
  {
   "title": "Submissions",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "import \"experimental/array\"\r\n\r\nvds_count = from(bucket: \"${bucket}\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n  |> filter(fn: (r) => r._measurement == \"component_event\" and r.component_name == \"Submitter\" and (r._field == \"VDS\" or r._field == \"message\"))\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.VDS == 1)\r\n  |> keep(columns: [\"message\"])\r\n  |> unique(column: \"message\")\r\n  |> count(column: \"message\")\r\n  |> map(fn: (r) => ({ event: \"VDS\", count: r.message })) // Standardize output structure\r\n\r\npatch_count = from(bucket: \"${bucket}\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n  |> filter(fn: (r) => r._measurement == \"component_event\" and r.component_name == \"Submitter\" and (r._field == \"PATCH\" or r._field == \"message\"))\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r.PATCH == 1)\r\n  |> keep(columns: [\"message\"])\r\n  |> unique(column: \"message\")\r\n  |> count(column: \"message\")\r\n  |> map(fn: (r) => ({ event: \"PATCH\", count: r.message })) // Standardize output structure\r\n\r\ndefault_values = array.from(rows: [\r\n  {event: \"VDS\", count: 0},\r\n  {event: \"PATCH\", count: 0}\r\n])\r\n\r\nunion(tables: [default_values, vds_count, patch_count])\r\n  |> group(columns: [\"event\"])\r\n  |> sum(column: \"count\")\r\n  |> rename(columns: {\"count\": \"\"})\r\n"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "cpu_percentageBusy",
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n  |> filter(fn: (r) => r._measurement == \"cpu\" and r.host =~ /$server$/ and r.cpu == \"cpu-total\")\r\n  |> aggregateWindow(every: $inter, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      total: r.usage_user + r.usage_system + r.usage_softirq + r.usage_steal + r.usage_nice + r.usage_irq + r.usage_iowait + r.usage_guest + r.usage_guest_nice\r\n  }))\r\n  |> keep(columns: [\"_time\", \"usage_user\", \"usage_system\", \"usage_softirq\", \"usage_steal\", \"usage_nice\", \"usage_irq\", \"usage_iowait\", \"usage_guest\", \"usage_guest_nice\", \"total\"])\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Load averages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "system_load1",
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n  |> filter(fn: (r) => r._measurement == \"system\"  and r.host =~ /$server$/)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> keep(columns: [\"_time\", \"load1\", \"load5\", \"load15\"])\r\n  |> rename(columns: {load1: \"short\", load5: \"medium\", load15: \"long\"})\r\n  |> sort(columns: [\"_time\"], desc: false)\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Processes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_host: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n  |> filter(fn: (r) => r._measurement == \"processes\" and r.host =~ /$server$/)\r\n  |> group(columns: [\"_field\", \"host\"])\r\n  |> aggregateWindow(every: ${inter}, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> sort(columns: [\"_time\"], desc: false)\r\n  |> keep(columns: [\"_time\", \"running\", \"blocked\", \"sleeping\", \"zombies\"])\r\n",
     "select": [
      [
       { "params": [ "blocked" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "mem_inactive",
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n  |> filter(fn: (r) => r._measurement == \"mem\" and r.host =~ /$server$/)\r\n  |> group(columns: [\"_field\", \"host\"])\r\n  |> aggregateWindow(every: ${inter}, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> sort(columns: [\"_time\"], desc: false)\r\n  |> keep(columns: [\"_time\", \"host\", \"total\", \"used\", \"cached\", \"free\", \"buffered\"])\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Kernel",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "Context switches",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "alias": "$tag_host: $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "processes",
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n  |> filter(fn: (r) => r._measurement == \"kernel\" and r._field == \"context_switches\" and r.host =~ /$server$/)\r\n  |> group(columns: [\"_field\", \"host\"])\r\n  |> aggregateWindow(every: ${inter}, fn: mean, createEmpty: false)\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> rename(columns: {_value: \"context switches\"})\r\n  |> sort(columns: [\"_time\"], desc: false)\r\n",
       "select": [
        [
         { "params": [ "blocked" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    },
    {
     "title": "Forks",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "alias": "$tag_host: $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "kernel",
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n  |> filter(fn: (r) => r._measurement == \"kernel\" and r.host =~ /^${server}$/ and r._field == \"processes_forked\")\r\n  |> group(columns: [\"host\"])\r\n  |> aggregateWindow(every: ${inter}, fn: mean, createEmpty: false)\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> rename(columns: {_value: \"forks\"})\r\n  |> sort(columns: [\"_time\"], desc: false)\r\n  |> keep(columns: [\"_time\", \"host\", \"forks\"])\r\n",
       "select": [
        [
         { "params": [ "processes_forked" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$server$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Per-cpu usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage for $cpu",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
     "repeat": "cpu",
     "targets": [
      {
       "alias": "$tag_host: $cpu $col",
       "function": "mean",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "cpu_percentageBusy",
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n  |> filter(fn: (r) => r._measurement == \"cpu\" and r.host =~ /${server}/ and r.cpu == \"${cpu}\")\r\n  |> group(columns: [\"_field\", \"host\", \"cpu\"])\r\n  |> aggregateWindow(every: ${inter}, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> keep(columns: [\"_time\", \"host\", \"cpu\", \"usage_user\", \"usage_system\", \"usage_softirq\", \"usage_steal\", \"usage_nice\", \"usage_irq\", \"usage_iowait\", \"usage_guest\", \"usage_guest_nice\"])\r\n  |> sort(columns: [\"_time\"], desc: false)\r\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Disk space usage for $mountpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "repeat": "mountpoint"
  },
  {
   "title": "Disk usage for $mountpoint",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$tag_host: mountpoint $tag_path - $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "path", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "disk_total",
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n  |> filter(fn: (r) => r._measurement == \"disk\" and r.host =~ /${server}/ and r.path == \"${mountpoint}\")\r\n  |> filter(fn: (r) => r._field == \"total\" or r._field == \"used\")\r\n  |> group(columns: [\"host\", \"path\", \"_field\"])\r\n  |> aggregateWindow(every: ${inter}, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({\r\n      r with _value: float(v: r._value)  // Ensure consistent data type\r\n  }))\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> keep(columns: [\"_time\", \"host\", \"path\", \"total\", \"used\"])\r\n  |> sort(columns: [\"_time\"], desc: false)\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk inodes for $mountpoint",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "alias": "$tag_host: mountpoint $tag_path - $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "path", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "disk_inodes_free",
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n  |> filter(fn: (r) => r._measurement == \"disk\" and r.host =~ /${server}/ and r.path == \"${mountpoint}\" and r._field == \"inodes_used\")\r\n  |> group(columns: [\"host\", \"path\"])\r\n  |> aggregateWindow(every: ${inter}, fn: mean, createEmpty: false)\r\n  |> rename(columns: {_value: \"used\"})\r\n  |> keep(columns: [\"_time\", \"host\", \"path\", \"used\"])\r\n  |> sort(columns: [\"_time\"], desc: false)\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host: mountpoint $tag_path - $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" },
      { "key": "path", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "disk_inodes_free",
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n  |> filter(fn: (r) => r._measurement == \"disk\" and r.host =~ /${server}/ and r.path == \"${mountpoint}\" and (r._field == \"inodes_free\" or r._field == \"inodes_used\"))\r\n  |> group(columns: [\"host\", \"path\", \"_field\"])\r\n  |> aggregateWindow(every: ${inter}, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ r with total: r.inodes_free + r.inodes_used }))\r\n  |> keep(columns: [\"_time\", \"host\", \"path\", \"total\"])\r\n  |> sort(columns: [\"_time\"], desc: false)\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}