{
 "title": "Fuzzing",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "influxdb" },
   { "name": "bucket", "label": "bucket", "query": "artiphishell" },
   { "name": "inter", "label": "Sampling", "query": "10s,30s,1m,2m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  { "title": "AFL++", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Exec/s",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "query": "execs = from(bucket: \"${bucket}\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n  |> filter(fn: (r) => r._measurement == \"component_event\" and r.component_name == \"AFL++\" and r._field == \"EXECS_PER_SEC\")\r\n  |> keep(columns: [\"_time\", \"_value\", \"replica_id\", \"component_id\"])\r\n  |> aggregateWindow(every: 1m, fn: mean)\r\n\r\nmean_execs = execs\r\n  |> group(columns: [\"_time\"])\r\n  |> mean()\r\n  |> group()\r\n  |> map(fn: (r) => ({\r\n    _time: r._time,\r\n    _value: r._value,\r\n    type: \"Mean\"\r\n  }))\r\n\r\nmin_execs = execs\r\n  |> group(columns: [\"_time\"])\r\n  |> min()\r\n  |> group()\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> map(fn: (r) => ({\r\n    _time: r._time,\r\n    _value: r._value,\r\n    type: \"Min\"\r\n  }))\r\n\r\nmax_execs = execs\r\n  |> group(columns: [\"_time\"])\r\n  |> max()\r\n  |> group()\r\n  |> map(fn: (r) => ({\r\n    _time: r._time,\r\n    _value: r._value,\r\n    type: \"Max\"\r\n  }))\r\n\r\n\r\nunion(tables: [mean_execs, max_execs, min_execs])\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"type\"], valueColumn: \"_value\")"
    },
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n  |> filter(fn: (r) => r._measurement == \"component_event\" and r.component_name == \"AFL++\" and r._field == \"EXECS_PER_SEC\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> aggregateWindow(every: 1m, fn: sum)\r\n  |> rename(columns: {\"_value\": \"Total\"})\r\n  |> keep(columns: [\"Total\", \"_time\"])"
    }
   ]
  },
  {
   "title": "Total Crashes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n  |> filter(fn: (r) => r._measurement == \"component_event\" and r.component_name == \"AFL++\" and r._field == \"SAVED_CRASHES\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> aggregateWindow(every: 1m, fn: max, createEmpty: false) // Compute max for each 10-second window\r\n\r\n"
    }
   ]
  },
  {
   "title": "Max Depth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n  |> filter(fn: (r) => r._measurement == \"component_event\" and r.component_name == \"AFL++\" and r._field == \"MAX_DEPTH\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> aggregateWindow(every: 1m, fn: max, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "Pending Total",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n  |> filter(fn: (r) => r._measurement == \"component_event\" and r.component_name == \"AFL++\" and r._field == \"PENDING_TOTAL\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "Stability %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n  |> filter(fn: (r) => r._measurement == \"component_event\" and r.component_name == \"AFL++\" and r._field == \"STABILITY\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false) // Compute max for each 10-second window\r\n  "
    }
   ]
  },
  {
   "title": "Total Execs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n  |> filter(fn: (r) => r._measurement == \"component_event\" and r.component_name == \"AFL++\" and r._field == \"EXECS_DONE\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> aggregateWindow(every: ${inter}, fn: sum, createEmpty: false)\r\n  |> cumulativeSum(columns: [\"_value\"]) // Compute the cumulative sum for _value\r\n"
    }
   ]
  },
  {
   "title": "Cycles dones",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n  |> filter(fn: (r) => r._measurement == \"component_event\" and r.component_name == \"AFL++\" and r._field == \"CYCLES_DONE\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> aggregateWindow(every: ${inter}, fn: sum, createEmpty: false)\r\n  |> cumulativeSum(columns: [\"_value\"]) // Compute the cumulative sum for _value\r\n"
    }
   ]
  },
  {
   "title": "Pending favs",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n  |> filter(fn: (r) => r._measurement == \"component_event\" and r.component_name == \"AFL++\" and r._field == \"PENDING_FAVS\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "Corpus Favored",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n  |> filter(fn: (r) => r._measurement == \"component_event\" and r.component_name == \"AFL++\" and r._field == \"CORPUS_FAVORED\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> aggregateWindow(every: 1m, fn: max, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Bitmap Coverage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n  |> filter(fn: (r) => r._measurement == \"component_event\" and r.component_name == \"AFL++\" and r._field == \"BITMAP_CVG\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> aggregateWindow(every: 1m, fn: max, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "Cycles done without find",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n  |> filter(fn: (r) => r._measurement == \"component_event\" and r.component_name == \"AFL++\" and r._field == \"CYCLES_WO_FINDS\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> aggregateWindow(every: 1m, fn: min, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "Edges Found",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 15, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n  |> filter(fn: (r) => r._measurement == \"component_event\" and r.component_name == \"AFL++\" and r._field == \"EDGES_FOUND\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> aggregateWindow(every: 1m, fn: max, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "Corpus Imported",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 19 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n  |> filter(fn: (r) => r._measurement == \"component_event\" and r.component_name == \"AFL++\" and r._field == \"CORPUS_IMPORTED\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> aggregateWindow(every: 1m, fn: max, createEmpty: false)\r\n"
    }
   ]
  }
 ]
}