#!/bin/bash

set -x
set -e

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)

cd "$SCRIPT_DIR"

pdl --unlock || rm -rf pipeline.lock

(
    pushd ../../
    docker buildx build -t aixcc-codeql . --load
    popd
)
pdl


if [ ! -d targets-semis-harden-demo2 ]; then
    git clone https://github.com/shellphish-support-syndicate/targets-semis-harden-demo2.git
    pushd targets-semis-harden-demo2
    ./run.sh pull_source
    popd
fi
if [ ! -f targets-semis-harden-demo2.tar.gz ]; then
    tar -czvf targets-semis-harden-demo2.tar.gz -C targets-semis-harden-demo2 .
fi
if [ ! -f targets-semis-harden-demo2-metadata.yaml ]; then
    cp targets-semis-harden-demo2/project.yaml targets-semis-harden-demo2-metadata.yaml
fi

if [ -d backup ]; then
    pd restore ./backup/ --all
fi

pd inject codeql_create_db.target_with_sources 1 < targets-semis-harden-demo2.tar.gz
pd inject codeql_run_info_extraction.info_extraction_request 666 < reachability-request.yaml
pd inject codeql_run_info_extraction.info_extraction_request 667 < reachability-request-autogenerated.yaml

pd --verbose --debug-trace run
