ARG BASE_IMAGE=
FROM ${BASE_IMAGE}

ARG ISOLATED=
RUN test -z "${ISOLATED}" || echo "deb [trusted=yes arch=amd64] http://apt-mirror-$(grep DISTRIB_RELEASE= /etc/lsb-release | cut -d= -f2 | sed 's/\./-/g'):$(grep DISTRIB_RELEASE= /etc/lsb-release | cut -d= -f2 | sed 's/\.//g') $(grep DISTRIB_CODENAME /etc/lsb-release | cut -d= -f2) main universe" > /etc/apt/sources.list
RUN apt-get update && apt-get install -y python3 python3-pip python3-yaml rsync

# Copy the local ./shellphish within the CP docker in /shellphish
COPY ./shellphish /shellphish/

RUN cd /shellphish/wrap-lib && make
RUN mv /usr/bin/ld /usr/bin/ld.real
RUN cp /shellphish/wrap-lib/fucked_up_ld /usr/bin/ld