ARG OSS_FUZZ_BASE_BUILDER_IMAGE=

FROM ${OSS_FUZZ_BASE_BUILDER_IMAGE}

ENV CODEQL_VERSION="2.22.0"

RUN apt-get update && apt-get install -y wget

RUN mkdir -p /shellphish/ 

RUN cd /shellphish && wget "https://github.com/github/codeql-action/releases/download/codeql-bundle-v${CODEQL_VERSION}/codeql-bundle-linux64.tar.gz"
RUN cd /shellphish && wget "https://github.com/mikefarah/yq/releases/download/v4.43.1/yq_linux_amd64"
RUN cd /shellphish && tar -xzf /shellphish/codeql-bundle-linux64.tar.gz
