[package]
name = "concolic_trace_interpretation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

log = "*"
itertools = "*"
libafl = { path = "../../repos/LibAFL/libafl" }
libafl_bolts = { path = "../../repos/LibAFL/libafl_bolts" }
z3 = { git = "https://github.com/Lukas-Dresel/z3.rs", branch = "feat/z3_information_extraction" }