#!/bin/bash -eu
# Copyright 2016 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
################################################################################

# If LLVM once again does weird changes then enable this:
#export AFL_LLVM_INSTRUMENT=LLVM-NATIVE

set -euo pipefail

pwd > /dev/stderr
env | grep SRC > /dev/stderr
ls -al "$SRC/" > /dev/stderr
ls -al "$SRC/shellphish/" > /dev/stderr
ls -al "$SRC/shellphish/aflplusplus/" > /dev/stderr

# AFL++ setup
echo "Copying precompiled AFL++"
# Copy AFL++ tools necessary for fuzzing.
pushd $SRC/shellphish/aflplusplus > /dev/null

cp -f libAFLDriver.a $LIB_FUZZING_ENGINE

# Some important projects include libraries, copy those even when they don't
# start with "afl-". Use "sort -u" to avoid a warning about duplicates.
ls afl-* *.txt *.a *.o *.so | sort -u | xargs cp -t $OUT

if [ "${ARTIPHISHELL_CCACHE_DISABLE:-}" = "1" ]; then
    export CC="$SRC/shellphish/aflplusplus/afl-clang-fast"
    export CXX="$SRC/shellphish/aflplusplus/afl-clang-fast++"
else
    export CC="ccache $SRC/shellphish/aflplusplus/afl-clang-fast"
    export CXX="ccache $SRC/shellphish/aflplusplus/afl-clang-fast++"
fi

# Set sane AFL++ environment defaults:
# Be quiet, otherwise this can break some builds.
export AFL_QUIET=1
# No leak errors during builds.
export ASAN_OPTIONS="detect_leaks=0:symbolize=0:detect_odr_violation=0:abort_on_error=1"
# Do not abort on any problems (because this is during build where it is ok)
export AFL_IGNORE_PROBLEMS=1
# No complain on unknown AFL environment variables
export AFL_IGNORE_UNKNOWN_ENVS=1

export AFL_LLVM_USE_TRACE_PC=1
export AFL_LLVM_DICT2FILE="$OUT/afl++.dict"
export AFL_LLVM_DICT2FILE_NO_MAIN=1
export AFL_MAP_SIZE=2621440

export CFLAGS="-g"
export CXXFLAGS="-g"
# DO NOT TRY TO EXPORT LDFLAGS, oss-fuzz targets just ignore it.
# Instead, you have to do `-Wl` in CFLAGS and CXXFLAGS.

# Provide a way to document the AFL++ options used in this build:
echo
echo AFL++ target compilation setup:
env | egrep '^AFL_' | tee "$OUT/shellphish_aijon_options.txt"
echo

popd > /dev/null

echo " done."
