repo_classes:
  my_workingTargets: FilesystemRepository
  my_AflPPinstallResults: FilesystemRepository
  my_AflPPCmplogInstallResults: FilesystemRepository

imports:
  libfuzzer:
    path: ../../pipeline.yaml
