# Base image
FROM neo4j:5.15
LABEL org.opencontainers.image.source=https://github.com/aixcc-sc/asc-crs-shellphish

# copy the data directory from the data image
ADD ./knowledge-base-generic-c-data.tar.gz  /
RUN mv /knowledge-base-generic-c-data /knowledge-base-data
RUN rm -f /knowledge-base-data/run/*

ENV NEO4J_HOME=/knowledge-base-data/

ADD entrypoint.sh /entrypoint.sh
ENTRYPOINT [ "/entrypoint.sh" ]
