[package]
name = "distributed_solver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "^2.33.3"
prost = "^0.8.0"
prost-types = "^0.8.0"
tokio = "^1.12.0"
smt2 = "^0.2.0"
num-traits = "^0.2.14"
bitvec = "^0.22.3"
multimap = "^0.8.3"

[build-dependencies]
prost-build = { version = "0.8.0" }