nameOverride: "example"
fullnameOverride: "example"

crsImage: "aixcc-example-server:latest"

# Set the chosen port below
service:
  type: ClusterIP
  port: 5000

resources:
  limits:
    cpu: 10000m
    memory: 10Gi
  requests:
    cpu: 5000m
    memory: 6Gi

volumeMounts:
- name: host-shared
  mountPath: /shared

nodeSelector: {}
tolerations: []
affinity: {}

replicaCount: 1
image:
  pullPolicy: Always
imagePullSecrets:
  - name: acr-docker-secret
  - name: ci-acr-pull-secret

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: "example-sa"

podAnnotations: {}
podLabels:
  support.shellphish.net/packing-group: any
podSecurityContext: {}
securityContext: {}


livenessProbe: {} # TODO this should be setup
readinessProbe: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes:
- name: host-shared
  hostPath:
    path: /shared
    type: DirectoryOrCreate

env: {}