apiVersion: v1
kind: Service
metadata:
  name: {{ include "telegraf.fullname" . }}
  labels:
    {{- include "telegraf.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  internalTrafficPolicy: Local
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: otlp
    {{- with .Values.service.additionalPorts }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  selector:
    {{- include "telegraf.selectorLabels" . | nindent 4 }}
