#!/bin/bash -eu
# Copyright 2016 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
################################################################################

# If LLVM once again does weird changes then enable this:
#export AFL_LLVM_INSTRUMENT=LLVM-NATIVE

set -euo pipefail

pwd > /dev/stderr
env | grep SRC > /dev/stderr
ls -al "$SRC/" > /dev/stderr

export CC="clang"
export CXX="clang++"

export CC=clang
export CXX=clang++
export CFLAGS="-g"
export CXXFLAGS="-g"
# DO NOT TRY TO EXPORT LDFLAGS, oss-fuzz targets just ignore it.
# Instead, you have to do `-Wl` in CFLAGS and CXXFLAGS.
export LIB_FUZZING_ENGINE=/usr/lib/libFuzzingEngine.a
export ASAN_OPTIONS=abort_on_error=1:detect_leaks=0
export ANTI_WRAP_LD_DEBUGGING=1

$CC $CFLAGS -c -o $SRC/shellphish/generic_harness.o $SRC/shellphish/generic_harness.c
ar rcs $SRC/shellphish/libgeneric_harness.a $SRC/shellphish/generic_harness.o
cp $SRC/shellphish/libgeneric_harness.a $LIB_FUZZING_ENGINE

echo " done."
