apiVersion: v1
kind: Secret
metadata:
  name: acr-docker-secret
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"auth\":\"%s\"}}}" .Values.global.acr.server (printf "%s:%s" .Values.global.acr.username .Values.global.acr.password | b64enc) | b64enc }} 
---
apiVersion: v1
kind: Secret
metadata:
  name: ci-acr-pull-secret
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"auth\":\"%s\"}}}" .Values.global.ci_acr.server (printf "%s:%s" .Values.global.ci_acr.username .Values.global.ci_acr.password | b64enc) | b64enc }} 
---
apiVersion: v1
kind: Secret
metadata:
  name: agent-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  AGENT_SECRET: {{ .Values.global.agentSecret.value }} 
---
apiVersion: v1
kind: Secret
metadata:
  name: ci-worker-token
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  CI_WORKER_TOKEN: {{ .Values.global.ci_worker_token.value }} 