apiVersion: v1
kind: Service
metadata:
  name: {{ include "telemetrydb.fullname" . }}
  labels:
    {{- include "telemetrydb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: influxdb
    {{- with .Values.service.additionalPorts }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  selector:
    {{- include "telemetrydb.selectorLabels" . | nindent 4 }}
