version: '3'
services:
  neo4j:
    build: ./.devcontainer/
    environment:
      NEO4J_AUTH: neo4j/Hacking!
    volumes:
      - .:/workspaces/knowledge-base
    ports:
      - "7474:7474"
      - "7687:7687"