apiVersion: v1
kind: Service
metadata:
  name: {{ include "permanence.fullname" . }}
  labels:
    {{- include "permanence.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- with .Values.service.additionalPorts }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  selector:
    {{- include "permanence.selectorLabels" . | nindent 4 }}
