ARG BASE_IMAGE=
ARG PREBUILD_IMAGE=

FROM ${PREBUILD_IMAGE} AS prebuild
FROM ${BASE_IMAGE}

RUN apt-get update && apt-get install -y software-properties-common

# Copy LLVM files from prebuild
COPY --from=prebuild /usr/lib/llvm-15 /usr/lib/llvm-15
COPY --from=prebuild /usr/bin/llvm* /usr/bin/
COPY --from=prebuild /usr/bin/clang* /usr/bin/
COPY --from=prebuild /usr/bin/lld* /usr/bin/

ENV RUN_FUZZER_MODE="interactive"
ENV ASAN_OPTIONS="alloc_dealloc_mismatch=0:allocator_may_return_null=1:allocator_release_to_os_interval_ms=500:check_malloc_usable_size=0:detect_container_overflow=1:detect_odr_violation=0:detect_leaks=1:detect_stack_use_after_return=1:fast_unwind_on_fatal=0:handle_abort=1:handle_segv=1:handle_sigill=1:max_uar_stack_size_log=16:print_scariness=1:quarantine_size_mb=10:strict_memcmp=1:strip_path_prefix=/workspace/:symbolize=1:use_sigaltstack=1:dedup_token_length=3"
ENV MSAN_OPTIONS="print_stats=1:strip_path_prefix=/workspace/:symbolize=1:dedup_token_length=3"
ENV UBSAN_OPTIONS="print_stacktrace=1:print_summary=1:silence_unsigned_overflow=1:strip_path_prefix=/workspace/:symbolize=1:dedup_token_length=3"
ENV FUZZER_ARGS="-rss_limit_mb=2560 -timeout=25"
ENV AFL_FUZZER_ARGS="-m none"

COPY yq /usr/local/bin/
COPY yq /usr/bin/
COPY run_fuzzer /usr/local/bin/
COPY parse_options.py /usr/local/bin/
