##############################################################################
#  This Dockerfile builds on top of the Dockerfile of the CP given by DARPA.
#  Requirements:
#    -> R1: A folder ./shellphish exists in the working directory
##############################################################################

ARG BASE_IMAGE=
FROM ${BASE_IMAGE} 

ARG ISOLATED=
RUN test -z "${ISOLATED}" || echo "deb [trusted=yes arch=amd64] http://apt-mirror-$(grep DISTRIB_RELEASE= /etc/lsb-release | cut -d= -f2 | sed 's/\./-/g'):$(grep DISTRIB_RELEASE= /etc/lsb-release | cut -d= -f2 | sed 's/\.//g') $(grep DISTRIB_CODENAME /etc/lsb-release | cut -d= -f2) main universe" > /etc/apt/sources.list
RUN apt-get update && apt-get install -y python3 python3-dev python3-pip rsync python3-yaml

# # Create the shellphish folder in challenge container too
RUN mkdir -p /shellphish

COPY ./shellphish/btrace-v2.2.5.tar.gz /shellphish/
RUN cd /shellphish && ls -la btrace-v2.2.5.tar.gz
RUN cd /shellphish && tar -xzf btrace-v2.2.5.tar.gz && mv btrace-v2.2.5 btrace

# overwrite the real jazzer
RUN mv /classpath/jazzer/jazzer /classpath/jazzer/jazzer_real
COPY ./shellphish/in_docker_jtrace.sh /classpath/jazzer/jazzer
RUN chmod +x /classpath/jazzer/jazzer