# aixcc-build: aixcc-dependencies-base

ARG SOURCE_REPO=https://github.com/shellphish-support-syndicate/artiphishell

FROM docker.io/library/ubuntu:22.04@sha256:340d9b015b194dc6e2a13938944e0d016e57b9679963fdeb9ce021daac430221

LABEL org.opencontainers.image.source=${SOURCE_REPO}

RUN apt-get update && apt-get install -y clang-14 python-is-python3 python3-pip rsync wget curl git jq
RUN apt-get update && apt-get install -y busybox-static python3 wget bc binutils bison build-essential
RUN apt-get update && apt-get install -y dwarves flex gcc git gnupg2 gzip libelf-dev libncurses5-dev
RUN apt-get update && apt-get install -y libssl-dev make openssl pahole perl-base rsync tar xz-utils
RUN apt-get update && apt-get install -y tmux vim nano procps iputils-ping net-tools iproute2 sudo
RUN apt-get update && apt-get install -y ca-certificates curl wget python3 python3-dev python3-pip python3-venv vim git rsync && \
	install -m 0755 -d /etc/apt/keyrings && \
	curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc && \
	chmod a+r /etc/apt/keyrings/docker.asc && \
	echo \
	  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
	  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" >/etc/apt/sources.list.d/docker.list && \
	apt-get update && apt-get install -y docker-ce-cli docker-buildx-plugin docker-compose-plugin

RUN DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get -y install tzdata

RUN pip install requests ipython ipdb jinja2

RUN mkdir -p /shellphish

WORKDIR /shellphish

####################### AFL++ BUILD ########################

# FROM ubuntu:22.04
RUN apt-get update && \
    apt-get install -y \
    make \
    autoconf \
    libtool \
    wget \
    ccache \
    build-essential \
    python3-dev \
    python3-setuptools \
    automake \
    cmake \
    git \
    flex \
    bison \
    libglib2.0-dev \
    libpixman-1-dev \
    cargo \
    libgtk-3-dev \
    python-is-python3 \
    python3-pip \
    rsync \
    jq \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common \
    clang-14 clang
RUN apt-get update && apt-get install -y patchelf strace ltrace htop procps

ENV PATH="/usr/lib/ccache:$PATH" \
    CCACHE_DIR=/shared/ccache \
    CCACHE_MAXSIZE=100G

######################### SYZKALLER #######################
RUN apt-get update && apt-get install -y \
    wget \
    git \
    make \
    gcc \
    flex \
    bison \
    libncurses-dev \
    libelf-dev \
    libssl-dev \
    build-essential \
    g++ \
    qemu-system-x86 \
    zip \
    unzip \
    debootstrap \
    bc \
    rsync \
    python3-pip \
    python3

RUN apt-get update && apt-get install -y curl

RUN pip install watchdog

# Download and extract Go
RUN wget https://dl.google.com/go/go1.21.4.linux-amd64.tar.gz \
    && tar -xf go1.21.4.linux-amd64.tar.gz \
    && rm go1.21.4.linux-amd64.tar.gz

# install virtme for kernel testing
# RUN echo deb http://ppa.launchpad.net/arighi/virtme-ng/ubuntu jammy main >>/etc/apt/sources.list && \
#     echo deb-src http://ppa.launchpad.net/arighi/virtme-ng/ubuntu jammy main >>/etc/apt/sources.list && \
#     apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 882A7727752A6461FCDDCFE5DCFA0E1546589D85 && \
#     apt-get update
# RUN DEBIAN_FRONTEND=noninteractive apt-get install -y virtme-ng libvirt-daemon-system

# Set environment variables
#RUN curl https://dl.google.com/go/go1.21.4.linux-amd64.tar.gz | tar -C /usr/local -xz
#ENV PATH /usr/local/go/bin:/gopath/bin:$PATH
#ENV GOPATH /gopath
ENV GOROOT /shellphish/go
ENV PATH $GOROOT/bin:$PATH
####### SYZKALLER BUILD ########
RUN apt-get update && apt-get install -y make gcc flex bison libncurses-dev libelf-dev libssl-dev wget clang-format clang llvm python3
#################### END SYZKALLER #############################

RUN apt install -y python3-pip
RUN pip3 install -U pip petname


RUN cd /tmp && wget https://github.com/mikefarah/yq/releases/download/v4.44.1/yq_linux_amd64.tar.gz -O - | tar xz && cp yq_linux_amd64 /usr/bin/yq && mv yq_linux_amd64 /usr/local/bin/yq

RUN apt-get update && apt-get install -y openjdk-17-jdk
RUN apt -y update && apt -y install inotify-tools
RUN apt update -y && apt install -y python3 python3-pip git bash rsync curl wget build-essential
RUN pip install PyYAML argparse pysarif pandas antlr4-tools antlr4-python3-runtime tqdm dask[complete]

############################# SNAPCHANGE ############################

# QEMU deps
# ENV DEBIAN_FRONTEND=noninteractive
# RUN apt-get update && apt -y install gcc-9 g++-9 clang make ninja-build debootstrap libelf-dev libssl-dev pkg-config
# RUN apt-get update && apt -y install libglib2.0-dev libgcrypt20-dev zlib1g-dev autoconf automake libtool bison flex libpixman-1-dev
# RUN apt-get update && apt -y install unar
# RUN apt-get update && apt -y install cpio
# RUN apt-get update && apt-get install -y lcov
#
#
# # Install rustup
# RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > /tmp/install_rust.sh && \
#     chmod +x /tmp/install_rust.sh && \
#     /tmp/install_rust.sh --default-toolchain nightly -y && \
#     rm /tmp/install_rust.sh

########################### END SNAPCHANGE #########################


###### LLVM Builds For 22.04 and 20.04 ######
RUN mkdir -p /llvm && chmod 777 /llvm
RUN wget https://github.com/llvm/llvm-project/releases/download/llvmorg-17.0.6/clang+llvm-17.0.6-x86_64-linux-gnu-ubuntu-22.04.tar.xz \
        -O /llvm/clang-17-22.04.tar.gz 2>/dev/null
RUN wget https://github.com/amyb-asu/llvm-build/releases/download/llvm-16-20.04/clang-16-20.04.tar.gz \
        -O /llvm/clang-16-20.04.tar.gz 2>/dev/null

####### Rust my beloved #######
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > /shellphish/rustup.sh
RUN bash /shellphish/rustup.sh -y
ENV PATH="/root/.cargo/bin:${PATH}"
RUN cargo --help

### ORGANIZERS + CLUSTERFUZZ
RUN apt-get update && apt-get install -y python3.11-venv

####################### NO BOYS ALLOWED ########################
RUN mv /usr/bin/docker /usr/bin/.docker.wrapped
COPY docker/docker /usr/bin/docker
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && chmod +x kubectl && mv kubectl /usr/bin/kubectl

RUN apt-get update && apt-get install patchelf htop procps strace ltrace

RUN apt-get update && apt-get install -y clang-14 python-is-python3
RUN pip install jsonschema

RUN apt-get update && apt-get install -y gdb gdbserver socat unar
RUN pip install tree-sitter==0.21.3 tree-sitter-languages==1.10.2 jq

COPY libs/libfreedom/ /shellphish/libs/libfreedom/
COPY libs/c-instrumentation/ /shellphish/libs/c-instrumentation/

WORKDIR /shellphish
