#!/bin/bash

set -x
set -e
set -u

IS_LOCAL_RUN=${IS_LOCAL_RUN:-0}

export ARTIPHISHELL_FUZZER_SYNC_BASE_DIR="/shared/fuzzer_sync"

export ARTIPHISHELL_PROJECT_NAME=$ARTIPHISHELL_PROJECT_NAME
export ARTIPHISHELL_PROJECT_ID=$ARTIPHISHELL_PROJECT_ID
export ARTIPHISHELL_HARNESS_NAME=$ARTIPHISHELL_HARNESS_NAME
export ARTIPHISHELL_HARNESS_INFO_ID=$ARTIPHISHELL_HARNESS_INFO_ID
export ARTIPHISHELL_FUZZER_SYNC_KICKSTART="${ARTIPHISHELL_FUZZER_SYNC_BASE_DIR}/${ARTIPHISHELL_PROJECT_NAME}-${ARTIPHISHELL_HARNESS_NAME}-${ARTIPHISHELL_HARNESS_INFO_ID}/sync-corpusguy-kickstart/queue"
export ARTIPHISHELL_FUZZER_SYNC_KICKSTART_CRASHES="${ARTIPHISHELL_FUZZER_SYNC_BASE_DIR}/${ARTIPHISHELL_PROJECT_NAME}-${ARTIPHISHELL_HARNESS_NAME}-${ARTIPHISHELL_HARNESS_INFO_ID}/sync-corpusguy-kickstart-crashes/queue"
export ARTIPHISHELL_FUZZER_SYNC_QUEUE="${ARTIPHISHELL_FUZZER_SYNC_BASE_DIR}/${ARTIPHISHELL_PROJECT_NAME}-${ARTIPHISHELL_HARNESS_NAME}-${ARTIPHISHELL_HARNESS_INFO_ID}/sync-corpusguy/queue"
export ARTIPHISHELL_FUZZER_SYNC_GRAMMARS="${ARTIPHISHELL_FUZZER_SYNC_BASE_DIR}/${ARTIPHISHELL_PROJECT_NAME}-${ARTIPHISHELL_HARNESS_NAME}-${ARTIPHISHELL_HARNESS_INFO_ID}/sync-grammars/nautilus-python"
export ARTIPHISHELL_FUZZER_SYNC_DICTS="${ARTIPHISHELL_FUZZER_SYNC_BASE_DIR}/${ARTIPHISHELL_PROJECT_NAME}-${ARTIPHISHELL_HARNESS_NAME}-${ARTIPHISHELL_HARNESS_INFO_ID}/sync-dicts"

# export to spot undefined variables
export PROJECT_METADATA_PATH=$PROJECT_METADATA_PATH
export HARNESS_INFO_PATH=$HARNESS_INFO_PATH
export CANONICAL_BUILD_ARTIFACT=$CANONICAL_BUILD_ARTIFACT
export FUNCTIONS_INDEX_PATH=$FUNCTIONS_INDEX_PATH
export FUNCTIONS_JSONS_DIR_PATH=$FUNCTIONS_JSONS_DIR_PATH

export OUTPUT_CORPUS_PATH=$OUTPUT_CORPUS_PATH
export OUTPUT_GRAMMARS_PATH=$OUTPUT_GRAMMARS_PATH
export OUTPUT_DICTIONARIES_PATH=$OUTPUT_DICTIONARIES_PATH
export OUTPUT_METADATA_PATH=$OUTPUT_METADATA_PATH

export INPUT_CORPUS_FILTERED_PATH=/shellphish/corpus-filtered
export INPUT_CORPUS_UNFILTERED_PATH=/shellphish/corpus-unfiltered
export INPUT_CORPUS_KICKSTART_PATH=/shellphish/corpus-kickstart
export INPUT_CORPUS_GRAMMARS_PATH=/shellphish/corpus-grammars
export INPUT_CORPUS_PERMANENCE_PATH=/shellphish/corpus-permanence
export INPUT_DICTIONARIES_PATH=/shellphish/dictionaries

export ARTIPHISHELL_FUZZER_SYNC_BASE_DIR=$ARTIPHISHELL_FUZZER_SYNC_BASE_DIR
export ARTIPHISHELL_FUZZER_SYNC_KICKSTART=$ARTIPHISHELL_FUZZER_SYNC_KICKSTART
export ARTIPHISHELL_FUZZER_SYNC_KICKSTART_CRASHES=$ARTIPHISHELL_FUZZER_SYNC_KICKSTART_CRASHES
export ARTIPHISHELL_FUZZER_SYNC_QUEUE=$ARTIPHISHELL_FUZZER_SYNC_QUEUE
export ARTIPHISHELL_FUZZER_SYNC_DICTS=$ARTIPHISHELL_FUZZER_SYNC_DICTS
mkdir -p "$ARTIPHISHELL_FUZZER_SYNC_KICKSTART" "$ARTIPHISHELL_FUZZER_SYNC_KICKSTART_CRASHES" "$ARTIPHISHELL_FUZZER_SYNC_QUEUE" "$ARTIPHISHELL_FUZZER_SYNC_GRAMMARS" "$ARTIPHISHELL_FUZZER_SYNC_DICTS"

mkdir -p /shared/corpusguy/
TMPDIR=$(mktemp -d -p /shared/corpusguy/)
rsync -ra "$CANONICAL_BUILD_ARTIFACT"/ "$TMPDIR"/
export PROJECT_DIR=$TMPDIR

python3 /shellphish/corpusguy/run_inference_llm.py
python3 /shellphish/corpusguy/run_codeql_extract_dicts.py

rm -rf $TMPDIR
