#!/bin/bash

set -x
set -e
set -u

export LANGUAGE=$LANGUAGE
export ARTIPHISHELL_FUZZER_SYNC_BASE_DIR="/shared/fuzzer_sync"

export ARTIPHISHELL_MAX_SEEDS_TOTAL=$ARTIPHISHELL_MAX_SEEDS_TOTAL

export ARTIPHISHELL_PROJECT_NAME=$ARTIPHISHELL_PROJECT_NAME
export ARTIPHISHELL_PROJECT_ID=$ARTIPHISHELL_PROJECT_ID
export ARTIPHISHELL_HARNESS_NAME=$ARTIPHISHELL_HARNESS_NAME
export ARTIPHISHELL_HARNESS_INFO_ID=$ARTIPHISHELL_HARNESS_INFO_ID
export ARTIPHISHELL_FUZZER_SYNC_KICKSTART="${ARTIPHISHELL_FUZZER_SYNC_BASE_DIR}/${ARTIPHISHELL_PROJECT_NAME}-${ARTIPHISHELL_HARNESS_NAME}-${ARTIPHISHELL_HARNESS_INFO_ID}/sync-corpusguy-kickstart/queue"
export ARTIPHISHELL_FUZZER_SYNC_KICKSTART_CRASHES="${ARTIPHISHELL_FUZZER_SYNC_BASE_DIR}/${ARTIPHISHELL_PROJECT_NAME}-${ARTIPHISHELL_HARNESS_NAME}-${ARTIPHISHELL_HARNESS_INFO_ID}/sync-corpusguy-kickstart-crashes/queue"
export ARTIPHISHELL_FUZZER_SYNC_PERMANENCE="${ARTIPHISHELL_FUZZER_SYNC_BASE_DIR}/${ARTIPHISHELL_PROJECT_NAME}-${ARTIPHISHELL_HARNESS_NAME}-${ARTIPHISHELL_HARNESS_INFO_ID}/sync-corpusguy-permanence/queue"
export ARTIPHISHELL_FUZZER_SYNC_QUEUE="${ARTIPHISHELL_FUZZER_SYNC_BASE_DIR}/${ARTIPHISHELL_PROJECT_NAME}-${ARTIPHISHELL_HARNESS_NAME}-${ARTIPHISHELL_HARNESS_INFO_ID}/sync-corpusguy/queue"
export ARTIPHISHELL_FUZZER_SYNC_DICTS="${ARTIPHISHELL_FUZZER_SYNC_BASE_DIR}/${ARTIPHISHELL_PROJECT_NAME}-${ARTIPHISHELL_HARNESS_NAME}-${ARTIPHISHELL_HARNESS_INFO_ID}/sync-dicts"

export INPUT_CORPUS_FILTERED_PATH=/shellphish/corpus-filtered
export INPUT_CORPUS_UNFILTERED_PATH=/shellphish/corpus-unfiltered
export INPUT_CORPUS_KICKSTART_PATH=/shellphish/corpus-kickstart
export INPUT_CORPUS_KICKSTART_CRASHES_PATH=/shellphish/corpus-kickstart-crashes
export INPUT_CORPUS_GRAMMARS_PATH=/shellphish/corpus-grammars
export INPUT_CORPUS_PERMANENCE_PATH=/shellphish/corpus-permanence
export INPUT_DICTIONARIES_PATH=/shellphish/dictionaries

export ARTIPHISHELL_FUZZER_SYNC_BASE_DIR=$ARTIPHISHELL_FUZZER_SYNC_BASE_DIR
export ARTIPHISHELL_FUZZER_SYNC_KICKSTART=$ARTIPHISHELL_FUZZER_SYNC_KICKSTART
export ARTIPHISHELL_FUZZER_SYNC_KICKSTART_CRASHES=$ARTIPHISHELL_FUZZER_SYNC_KICKSTART_CRASHES
export ARTIPHISHELL_FUZZER_SYNC_PERMANENCE=$ARTIPHISHELL_FUZZER_SYNC_PERMANENCE
export ARTIPHISHELL_FUZZER_SYNC_QUEUE=$ARTIPHISHELL_FUZZER_SYNC_QUEUE
export ARTIPHISHELL_FUZZER_SYNC_DICTS=$ARTIPHISHELL_FUZZER_SYNC_DICTS
mkdir -p "$ARTIPHISHELL_FUZZER_SYNC_KICKSTART" "$ARTIPHISHELL_FUZZER_SYNC_KICKSTART_CRASHES" "$ARTIPHISHELL_FUZZER_SYNC_QUEUE" "$ARTIPHISHELL_FUZZER_SYNC_DICTS" "$ARTIPHISHELL_FUZZER_SYNC_PERMANENCE"

# DOWNLOAD PERMANENCE CORPUS
PERMANENCE_SERVER_URL=${PERMANENCE_SERVER_URL:-http://beatty.unfiltered.seclab.cs.ucsb.edu:31337}
mkdir -p $INPUT_CORPUS_PERMANENCE_PATH && \
# FIRST TRY PROJECT-HARNESS PAIR
curl -X GET \
     -H 'Shellphish-Secret: !!artiphishell!!' \
     -H 'Content-Type: application/json' \
     -H 'Accept: application/json' $PERMANENCE_SERVER_URL/download_corpus/${ARTIPHISHELL_PROJECT_NAME}/${ARTIPHISHELL_HARNESS_NAME} --fail --output /tmp/corpus-permanence.tar.gz ||
# OTHERWISE TRY HARNESS NAME ONLY
curl -X GET \
     -H 'Shellphish-Secret: !!artiphishell!!' \
     -H 'Content-Type: application/json' \
     -H 'Accept: application/json' $PERMANENCE_SERVER_URL/download_corpus/${ARTIPHISHELL_HARNESS_NAME} --fail --output /tmp/corpus-permanence.tar.gz && \
tar -xzf /tmp/corpus-permanence.tar.gz -C $INPUT_CORPUS_PERMANENCE_PATH

NUM_PERMANENCE_SEEDS=$(find $INPUT_CORPUS_PERMANENCE_PATH -type f | wc -l)
echo "Downloaded $NUM_PERMANENCE_SEEDS seeds from permanence corpus"

if [ "$CORPUSGUY_SYNC_TO_FUZZER" -eq 1 ]; then
    # COPY MAX $ARTIPHISHELL_MAX_SEEDS_TOTAL RANDOM SEEDS FROM PERMANENCE CORPUS TO $ARTIPHISHELL_FUZZER_SYNC_PERMANENCE
    i=1 && find $INPUT_CORPUS_PERMANENCE_PATH -type f | shuf -n $ARTIPHISHELL_MAX_SEEDS_TOTAL | while read file; do cp "$file" "${ARTIPHISHELL_FUZZER_SYNC_PERMANENCE}/id:$(printf %06d $i)_${file##*/}" && ((i++)); done
    
    # COPY MAX $ARTIPHISHELL_MAX_SEEDS_TOTAL RANDOM CRASHES TO ARTIPHISHELL_FUZZER_SYNC_KICKSTART_CRASHES
    find $INPUT_CORPUS_KICKSTART_CRASHES_PATH -type f | shuf -n $ARTIPHISHELL_MAX_SEEDS_TOTAL | xargs -I {} cp {} $ARTIPHISHELL_FUZZER_SYNC_KICKSTART_CRASHES/
fi

# SYNC KICKSTART CORPUS (OSS-FUZZ)
python3 /shellphish/corpusguy/run_kickstart.py

# FIND POSSIBLE TEST CASES
pushd $CANONICAL_BUILD_ARTIFACT
/shellphish/corpusguy/find_testcases.sh > /tmp/all_combined
popd
# Find current max ID in ARTIPHISHELL_FUZZER_SYNC_KICKSTART
max_id=$(find "$ARTIPHISHELL_FUZZER_SYNC_KICKSTART" -name "id:*" -type f 2>/dev/null | sed 's/.*id:\([0-9]*\).*/\1/' | sort -n | tail -1)
# Copy files from all_combined to kickstart directory (max 500)
i=$((${max_id:-0} + 1))
count=0
while IFS= read -r file && [ $count -lt 500 ]; do
    if [ -f "$file" ]; then
        hash=$(sha256sum "$file" | cut -d' ' -f1)
        cp "$file" "${ARTIPHISHELL_FUZZER_SYNC_KICKSTART}/id:$(printf %06d $i)_${hash}"
        ((i++))
        ((count++))
    fi
done < /tmp/all_combined