#!/bin/bash

set -x
set -e

docker login ghcr.io -u player-c3f09220 -p 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

pushd ../../../../../../
./rebuild.sh || true
popd
pushd ../../../../common/crs-utils
docker build -t aixcc-crs-utils .
popd
pushd ../../
docker build -t aixcc-syzkaller .
popd

if [ ! -d targets-semis-harden-demo2 ]; then
    git clone https://github.com/shellphish-support-syndicate/targets-semis-harden-demo2
    (
        pushd targets-semis-harden-demo2
        ./run.sh pull_source
        popd
    )
fi
if [ ! -f targets-semis-harden-demo2.tar.gz ]; then
    tar czf targets-semis-harden-demo2.tar.gz -C targets-semis-harden-demo2 .
fi

pdl --unlock || rm -rf pipeline.lock
pdl
pd inject syzkaller_build.kernel_target 1 < targets-semis-harden-demo2.tar.gz
pd inject codeql_run_info_extraction.info_extraction_request 666 < ../../../../common/codeql/feature_tests/harden-demo2/reachability-request-autogenerated.yaml
#pd -verbose --debug-trace run
