#!/bin/bash

set -x
set -e

pdl --unlock || rm -rf pipeline.lock
pdl

if [ ! -d targets-semis-harden-demo2 ]; then
    git clone https://github.com/shellphish-support-syndicate/targets-semis-harden-demo2
    (
        pushd targets-semis-harden-demo2
        make cpsrc-prepare
        popd
    )
fi
if [ ! -f targets-semis-harden-demo2.tar.gz ]; then
    tar czf targets-semis-harden-demo2.tar.gz -C targets-semis-harden-demo2 .
fi
pd inject syzkaller_build.kernel_target 1 < targets-semis-harden-demo2.tar.gz
pd inject codeql_run_info_extraction.info_extraction_request 666 < ../../../../common/codeql/feature_tests/harden-demo2/reachability-request-autogenerated.yaml

