#!/bin/bash

set -x
set -e
set -u

# export to spot undefined variables
export LANGUAGE=$LANGUAGE
export PROJECT_METADATA_PATH=$PROJECT_METADATA_PATH
export HARNESS_INFO_PATH=$HARNESS_INFO_PATH
export COVERAGE_BUILD_ARTIFACT=$COVERAGE_BUILD_ARTIFACT
export FUNCTIONS_INDEX_PATH=$FUNCTIONS_INDEX_PATH
export FUNCTIONS_JSONS_DIR_PATH=$FUNCTIONS_JSONS_DIR_PATH

export ARTIPHISHELL_PROJECT_ID=$ARTIPHISHELL_PROJECT_ID
export ARTIPHISHELL_PROJECT_NAME=$ARTIPHISHELL_PROJECT_NAME
export ARTIPHISHELL_HARNESS_NAME=$ARTIPHISHELL_HARNESS_NAME
export ARTIPHISHELL_HARNESS_INFO_ID=$ARTIPHISHELL_HARNESS_INFO_ID
export ARTIPHISHELL_FUZZER_SYNC_BASE_DIR="/shared/fuzzer_sync"
export ARTIPHISHELL_FUZZER_SYNC_DIR="${ARTIPHISHELL_FUZZER_SYNC_BASE_DIR}/${ARTIPHISHELL_PROJECT_NAME}-${ARTIPHISHELL_HARNESS_NAME}-${ARTIPHISHELL_HARNESS_INFO_ID}/"

mkdir -p /shared/ron-composer/$ARTIPHISHELL_PROJECT_ID/
TMPDIR=$(mktemp -d -p /shared/ron-composer/$ARTIPHISHELL_PROJECT_ID/)
rsync -ra "$COVERAGE_BUILD_ARTIFACT"/ "$TMPDIR"/
export PROJECT_DIR=$TMPDIR

function run_ron_composer() {
    # Wait for watchtower queue directory
    if [[ "$LANGUAGE" == "jvm" ]]; then
        export ARTIPHISHELL_RON_READ_SYNC_PATH=${ARTIPHISHELL_FUZZER_SYNC_DIR}/sync-jazzer-rons/queue
        export ARTIPHISHELL_RON_WRITE_SYNC_PATH=${ARTIPHISHELL_FUZZER_SYNC_DIR}/sync-jazzer-rons/queue
    else
        export ARTIPHISHELL_RON_READ_SYNC_PATH=${ARTIPHISHELL_FUZZER_SYNC_DIR}/nautilus/instances
        export ARTIPHISHELL_RON_WRITE_SYNC_PATH=${ARTIPHISHELL_FUZZER_SYNC_DIR}/nautilus/instances/composer/queue
    fi
    mkdir -p "$ARTIPHISHELL_RON_READ_SYNC_PATH"
    mkdir -p "$ARTIPHISHELL_RON_WRITE_SYNC_PATH"
    python3 /shellphish/grammar-composer/run_ron_composer.py
}

run_ron_composer

rm -rf $TMPDIR
