[package]
name = "sancov_instrumentation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]
bench = false

[dependencies]
libc = "*"
cty = "*"
log = "*"
sancov_shared = { path = "../sancov_shared", features = ["global_vars"]}
page_size = "*"

[features]
default = ["mode_ptrace", "pcs_table", "inline_bool_flags", "inline_8bit_counters", "trace_pc", "trace_pc_indirect", "pc_guards"]
pcs_table = []
trace_pc = []
trace_pc_indirect = []
pc_guards = []
inline_bool_flags = []
inline_8bit_counters = []

mode_ptrace = []
mode_shm = []