FROM alpine:latest

RUN wget https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.33.0/crictl-v1.33.0-linux-amd64.tar.gz && tar xzf crictl-v1.33.0-linux-amd64.tar.gz && chmod +x crictl


