#!/bin/bash

cd $(dirname $0)/..

set -e
set +x

. tmp/.env

export OPENAI_BUDGET=${OPENAI_BUDGET:-40}
export CLAUDE_BUDGET=${CLAUDE_BUDGET:-50}
export GEMINI_BUDGET=${GEMINI_BUDGET:-0.000001}

export GRAMMAR_BUDGET=${GRAMMAR_BUDGET:-40}
export GRAMMAR_BUDGET_OPENAI=${GRAMMAR_BUDGET_OPENAI:-10}
export PATCHING_BUDGET=${PATCHING_BUDGET:-50}

export TOTAL_LLM_TIME_MINUTES=${TOTAL_LLM_TIME_MINUTES:-240}
export ROLLING_PERIOD_MINUTES=${ROLLING_PERIOD_MINUTES:-5}

export FULL_MODE_TASKS=${FULL_MODE_TASKS:-6}
export DELTA_MODE_TASKS=${DELTA_MODE_TASKS:-9}
export FULL_MODE_TASK_LENGTH_MINUTES=${FULL_MODE_TASK_LENGTH_MINUTES:-1440}
export DELTA_MODE_TASK_LENGTH_MINUTES=${DELTA_MODE_TASK_LENGTH_MINUTES:-480}

#timeout 20 scripts/access_k8.sh 1>/dev/null

API_POD=$(kubectl get pod -l app.kubernetes.io/name=api -o jsonpath='{.items[0].metadata.name}')

echo "💸 Setting LLM budgets..."

set -x
kubectl exec -it $API_POD -- bash -c "TOTAL_LLM_TIME_MINUTES=$TOTAL_LLM_TIME_MINUTES ROLLING_PERIOD_MINUTES=$ROLLING_PERIOD_MINUTES OPENAI_BUDGET=$OPENAI_BUDGET CLAUDE_BUDGET=$CLAUDE_BUDGET GEMINI_BUDGET=$GEMINI_BUDGET GRAMMAR_BUDGET=$GRAMMAR_BUDGET GRAMMAR_BUDGET_OPENAI=$GRAMMAR_BUDGET_OPENAI PATCHING_BUDGET=$PATCHING_BUDGET FULL_MODE_TASKS=$FULL_MODE_TASKS DELTA_MODE_TASKS=$DELTA_MODE_TASKS FULL_MODE_TASK_LENGTH_MINUTES=$FULL_MODE_TASK_LENGTH_MINUTES DELTA_MODE_TASK_LENGTH_MINUTES=$DELTA_MODE_TASK_LENGTH_MINUTES /app/infra/api/scripts/set_llm_budget.py"

