repo_classes:
  cp_image_ready:  MetadataRepository
  crs_tasks_cancelled: MetadataRepository
  targets_with_sources: FilesystemRepository
  target_metadatas: MetadataRepository
  all_non_kernel_targets_with_sources: FilesystemRepository
  non_kernel_c_targets_with_sources: FilesystemRepository

  full_functions_indices: BlobRepository
  full_functions_jsons_dirs: FilesystemRepository
  full_functions_by_commit_jsons_dirs: FilesystemRepository
  full_functions_by_file_index_jsons: BlobRepository
  commit_functions_indices: BlobRepository
  commit_functions_jsons_dirs: FilesystemRepository

  target_harness_infos: MetadataRepository

  benign_harness_inputs: BlobRepository
  benign_harness_inputs_metadatas: MetadataRepository
  crashing_harness_inputs: BlobRepository
  crashing_harness_inputs_metadatas: MetadataRepository
  to_triage_harness_inputs: BlobRepository
  to_triage_harness_inputs_metadatas: MetadataRepository

  info_extraction_requests: MetadataRepository
  
  targets_built_with_coverage: FilesystemRepository
  unused_garbage_blob: BlobRepository
  unused_garbage_metadata: MetadataRepository
  unused_garbage_filesystem: FilesystemRepository

  fuzz_requests: MetadataRepository

# RepositoryTypes define storage / type of data - blob / metadata / filesystem
# LinkTypes define the way the data in these repos is handled - filesystem / metadata. 
# Metadata is used for keying and is being parsed by pd. PD propagates the keys through the pipeline
# First thing: Check ids for non-keyed repos. Then check the keys for the dependend repos. If all exists for key x - run, else wait.
imports:
  target-harness-splitter:
    path: ../../target-harness-splitter/pipeline.yaml
    repos:
      targets_with_sources: targets_with_sources
      target_harness_infos: target_harness_infos
      crs_tasks_cancelled: crs_tasks_cancelled

  target-identifier:
    path: ../../target-identifier/pipeline.yaml
    repos:
      targets_with_sources: targets_with_sources
      target_metadatas: target_metadatas
      crs_tasks_cancelled: crs_tasks_cancelled

  target-fuzz-requestor:
    path: ../../target-fuzz-requestor/pipeline.yaml
    repos:
      target_harness_infos: target_harness_infos
      info_extraction_requests: info_extraction_requests
      target_directed_fuzz_requests: fuzz_requests
      crs_tasks_cancelled: crs_tasks_cancelled
  
  coverage_guy: 
    path: ../../coverage-guy/pipeline_build.yaml
    repos: 
      # Inputs
      full_functions_indices: full_functions_indices
      targets_with_sources: targets_with_sources
      cp_image_ready: cp_image_ready
      target_metadata: target_metadatas
      crs_tasks_cancelled: crs_tasks_cancelled

      # Outputs
      targets_built_with_coverage: targets_built_with_coverage

  # clang_indexer:
  #   path: ../../clang-indexer/pipeline.yaml
  #   repos:
  #     c_targets_with_sources: targets_with_sources
  #     non_kernel_c_targets_with_sources: non_kernel_c_targets_with_sources
  #     target_metadatas: target_metadatas
  #     full_json_output_dirs: full_functions_jsons_dirs
  #     by_commit_json_output_dirs: commit_functions_jsons_dirs

  function_index_generator:
    path: ../../function-index-generator/pipeline.yaml
    repos:
      crs_tasks_cancelled: crs_tasks_cancelled
      commit_functions_jsons_dirs: commit_functions_jsons_dirs
      commit_functions_indices: commit_functions_indices
 
      full_functions_by_file_index_jsons: full_functions_by_file_index_jsons
      full_functions_jsons_dirs: full_functions_jsons_dirs
      full_functions_indices: full_functions_indices
 
      info_extraction_requests: info_extraction_requests

  grammar_guy:
    path: ../pipeline.yaml
    repos:
      crs_tasks_cancelled: crs_tasks_cancelled
      grammar_guy_built_targets: targets_built_with_coverage
      cp_image_ready: cp_image_ready
      fuzz_requests: fuzz_requests
      targets_with_sources: targets_with_sources
      target_harness_infos: target_harness_infos
      full_functions_indices: full_functions_indices
      full_functions_jsons_dirs: full_functions_jsons_dirs

      to_triage_harness_inputs: to_triage_harness_inputs
      to_triage_harness_inputs_metadatas: to_triage_harness_inputs_metadatas

      info_extraction_requests: info_extraction_requests
