[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "vuln_detect_model"
version = "0.1.0"
description = "vulnerability detection utilities"
