repo_classes:
  targets_with_sources: FilesystemRepository
  debug_built_targets_with_sources: FilesystemRepository
  target_metadatas: MetadataRepository
  cp_image_ready: MetadataRepository

  clang_indexer_meta_csvs: BlobRepository
  full_functions_indices: BlobRepository
  full_functions_jsons_dirs: FilesystemRepository
  full_functions_by_commit_jsons_dirs:
    cls: FilesystemRepository
    compress_backend: false
    compress_backup: false
  full_functions_by_file_index_jsons: BlobRepository
  commit_functions_indices: BlobRepository
  commit_functions_index_csvs: BlobRepository
  commit_functions_jsons_dirs:
    cls: FilesystemRepository
    compress_backend: false
    compress_backup: false

  target_harness_infos: MetadataRepository

  benign_harness_inputs: BlobRepository
  benign_harness_inputs_metadatas: MetadataRepository
  crashing_harness_inputs: BlobRepository
  crashing_harness_inputs_metadatas: MetadataRepository

  target_directed_fuzz_requests: MetadataRepository
  target_directed_fuzz_requests_seeds: FilesystemRepository
  info_extraction_requests: MetadataRepository

  codeql_reports: BlobRepository
  codeql_qlpack_reports: BlobRepository

  info_extraction_results: MetadataRepository
  kernel_reachability_results: MetadataRepository
  libfuzzer_reaching_functions_dicts: BlobRepository
  libfuzzer_reaching_files_dicts: BlobRepository
  
  pov_reports: MetadataRepository
  crash_run_pov_result_metadatas: MetadataRepository
  pov_report_representative_crashing_inputs: BlobRepository
  pov_report_representative_crashing_input_metadatas: MetadataRepository

imports:
  crs_utils:
    path: ../../../../common/base/crs-utils/pipeline.yaml
    repos:
      targets_with_sources: targets_with_sources
      debug_built_targets_with_sources: debug_built_targets_with_sources
      target_metadatas: target_metadatas
      target_harness_infos: target_harness_infos
      target_directed_fuzz_requests: target_directed_fuzz_requests
      info_extraction_requests: info_extraction_requests
      cp_image_ready: cp_image_ready
      crashing_harness_inputs: crashing_harness_inputs
      crashing_harness_inputs_metadatas: crashing_harness_inputs_metadatas
      pov_reports: pov_reports
      crash_run_pov_result_metadatas: crash_run_pov_result_metadatas
      pov_report_representative_crashing_inputs: pov_report_representative_crashing_inputs
      pov_report_representative_crashing_input_metadatas: pov_report_representative_crashing_input_metadatas
      
  svaultbard:
    path: ../../../../common/svaultbard/pipeline.yaml
    repos:
      targets_with_sources: targets_with_sources
      target_directed_fuzz_requests: target_directed_fuzz_requests
      target_harness_infos: target_harness_infos
      target_directed_seeds: target_directed_fuzz_requests_seeds

  clang_indexer:
    path: ../../../../common/clang-indexer/pipeline.yaml
    repos:
      c_targets_with_sources: targets_with_sources
      target_metadatas: target_metadatas
      full_json_output_dirs: full_functions_jsons_dirs
      by_commit_json_output_dirs: commit_functions_jsons_dirs

  function_index_generator:
    path: ../../../../common/function_index_generator/pipeline.yaml
    repos:
      full_functions_jsons_dirs: full_functions_jsons_dirs
      full_functions_index_csvs: clang_indexer_meta_csvs
      full_functions_indices: full_functions_indices
      full_functions_by_file_index_jsons: full_functions_by_file_index_jsons
      commit_functions_jsons_dirs: commit_functions_jsons_dirs
      commit_functions_index_csvs: commit_functions_index_csvs
      commit_functions_indices: commit_functions_indices
      info_extraction_requests: info_extraction_requests

  codeql:
    path: ../../../../common/codeql/pipeline.yaml
    repos:
      targets_with_sources: targets_with_sources
      target_metadatas: target_metadatas
      info_extraction_requests: info_extraction_requests
      codeql_reports: codeql_reports
      codeql_qlpack_reports: codeql_qlpack_reports
      info_extraction_results: info_extraction_results
      kernel_reachability_results: kernel_reachability_results
      libfuzzer_reaching_functions_dicts: libfuzzer_reaching_functions_dicts
      libfuzzer_reaching_files_dicts: libfuzzer_reaching_files_dicts

  libfuzzer:
    path: ../../pipeline.yaml
    repos:
      cp_image_ready: cp_image_ready
      targets_with_sources: targets_with_sources
      libfuzzer_harness_infos: target_harness_infos
      fuzz_requests: target_directed_fuzz_requests
      fuzz_requests_seeds: target_directed_fuzz_requests_seeds
      crashes: crashing_harness_inputs
      crashes_meta: crashing_harness_inputs_metadatas
      benign_harness_inputs: benign_harness_inputs
      benign_harness_inputs_meta: benign_harness_inputs_metadatas
      libfuzzer_reaching_functions_dicts: libfuzzer_reaching_functions_dicts
      libfuzzer_reaching_files_dicts: libfuzzer_reaching_files_dicts
