nameOverride: "permanence"
fullnameOverride: "permanence"

crsImage: "aixcc-permanence-server:latest"

# Set the chosen port below
service:
  type: ClusterIP
  port: 31337

resources:
  limits:
    cpu: 4000m
    memory: 4Gi
  requests:
    cpu: 2000m
    memory: 2Gi

volumeMounts:
- name: host-shared
  mountPath: /shared

nodeSelector:
  support.shellphish.net/only-storage: "true"

tolerations:
  - key: "support.shellphish.net/only-storage"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"

affinity: {}

replicaCount: 1
image:
  pullPolicy: Always
imagePullSecrets:
  - name: acr-docker-secret
  - name: ci-acr-pull-secret

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: "permanence-sa"

podAnnotations: {}
podLabels:
  support.shellphish.net/packing-group: any
podSecurityContext: {}
securityContext: {}


livenessProbe: {} # TODO this should be setup
readinessProbe: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes:
- name: host-shared
  hostPath:
    path: /shared
    type: DirectoryOrCreate

env: {}
