[package]
name = "path_coverage_tracker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]
bench = false

[dependencies]
lazy_static = "^1.4.0"
shared_memory = "^0.12.0"
prost = "^0.9.0"
prost-types="^0.9.0"
libc = "^0.2.103"
serde = { version = "^1.0.130", features = ["derive"] }
serde_json = "^1.0.68"
cty = "^0.2.2"
log = "^0.4.14"
env_logger = "^0.9.0"

[build-dependencies]
prost-build = "^0.9.0"