# aixcc-build: aixcc-test_harness_jenkins
ARG IMAGE_PREFIX=
FROM ${IMAGE_PREFIX}aixcc-component-base
LABEL org.opencontainers.image.source=https://github.com/aixcc-sc/asc-crs-shellphish

COPY ./jazzer_modifications /jazzer_modifications
