# aixcc-build: aixcc-svaultbard
ARG IMAGE_PREFIX=
FROM ${IMAGE_PREFIX}aixcc-dependencies-base
LABEL org.opencontainers.image.source=https://github.com/aixcc-sc/asc-crs-shellphish

COPY corpus /corpus
