ARG BASE_IMAGE=

# =======================================
# ====== START INSTALLING MYROCO ======== 
# =======================================
FROM ghcr.io/aixcc-finals/base-runner:v1.2.0 AS myroco

ENV BAZELISK_VERSION 1.9.0
RUN curl -L https://github.com/bazelbuild/bazelisk/releases/download/v$BAZELISK_VERSION/bazelisk-linux-amd64 -o /usr/local/bin/bazel && \
    chmod +x /usr/local/bin/bazel

# Copy the jazzer-aixcc folder to the image
RUN mkdir -p /shellphish/myroco


# bazel complains if the user is root so we create a new user
RUN useradd -m myre
USER myre

RUN mkdir -p /home/myre/myroco

# jazzer-aixcc is https://github.com/aixcc-finals/jazzer-aixcc/commit/efbc6354e412ce221ad3b18a6fdd32bf12241825
RUN echo 1 && cd /home/myre/myroco && git clone https://github.com/aixcc-finals/jazzer-aixcc jazzer-aixcc
RUN cd /home/myre/myroco/jazzer-aixcc && git checkout efbc6354e412ce221ad3b18a6fdd32bf12241825
COPY --chown=myre:myre jazzer-aixcc-patches /home/myre/myroco/jazzer-aixcc-patches


RUN cd /home/myre/myroco/jazzer-aixcc && git apply /home/myre/myroco/jazzer-aixcc-patches/*.patch
RUN cd /home/myre/myroco/jazzer-aixcc && bazel build //src/main/java/com/code_intelligence/jazzer:jazzer_standalone_deploy.jar //deploy:jazzer-api //deploy:jazzer-junit //launcher:jazzer

RUN mkdir /home/myre/myroco/jazz-build

RUN cd /home/myre/myroco/jazzer-aixcc && cp $(bazel cquery --output=files //src/main/java/com/code_intelligence/jazzer:jazzer_standalone_deploy.jar) /home/myre/myroco/jazz-build/jazzer_agent_deploy.jar
RUN cd /home/myre/myroco/jazzer-aixcc && cp $(bazel cquery --output=files //launcher:jazzer) /home/myre/myroco/jazz-build/jazzer_driver

RUN md5sum /home/myre/myroco/jazz-build/jazzer_agent_deploy.jar
RUN md5sum /home/myre/myroco/jazz-build/jazzer_driver