# aixcc-build: aixcc-antlr4-parser

ARG SOURCE_REPO=https://github.com/shellphish-support-syndicate/artiphishell

FROM python:3.10

LABEL org.opencontainers.image.source=${SOURCE_REPO}
RUN pip install antlr4-tools antlr4-python3-runtime argparse tqdm GitPython jsonschema pyyaml numpy requests
RUN git config --global --add safe.directory '*'
WORKDIR /app
COPY . /app

# for development and local testing, this will be read as an environment variable during the game
ENV RETRIEVAL_API='http://beatty.unfiltered.seclab.cs.ucsb.edu:48751'
