ARG OSS_FUZZ_BASE_BUILDER_IMAGE=

FROM ${OSS_FUZZ_BASE_BUILDER_IMAGE}

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    libncurses5 lsb-release software-properties-common

RUN wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && ./llvm.sh 18 && rm llvm.sh