repo_classes:
  cp_image_ready: MetadataRepository
  raw_targets_with_sources: FilesystemRepository
  targets_with_sources: FilesystemRepository
  c_targets_with_sources: FilesystemRepository
  java_targets_with_sources: FilesystemRepository
  all_non_kernel_targets_with_sources: FilesystemRepository
  non_kernel_c_targets_with_sources: FilesystemRepository
  debug_built_targets_with_sources: FilesystemRepository

  target_metadatas: MetadataRepository
  harness_infos: MetadataRepository

  info_extraction_requests: MetadataRepository
  target_directed_fuzz_requests: MetadataRepository
  target_directed_seeds: FilesystemRepository

  codeql_reports: BlobRepository
  codeql_qlpack_reports: BlobRepository
  codeql_targets_strings: FilesystemRepository
  
  kernel_reachability_results: MetadataRepository
  info_extraction_results: MetadataRepository

  full_functions_indices: BlobRepository
  full_functions_index_csvs: BlobRepository
  full_functions_jsons_dirs: FilesystemRepository
  full_functions_by_file_index_jsons: BlobRepository

  commit_functions_indices: BlobRepository
  commit_functions_index_csvs: BlobRepository
  commit_functions_jsons_dirs: FilesystemRepository

  libfuzzer_reaching_functions_dicts: BlobRepository
  libfuzzer_reaching_files_dicts: BlobRepository

  target_start_times: MetadataRepository

  crashing_harness_inputs: BlobRepository
  crashing_harness_inputs_metadatas: MetadataRepository
  crash_run_pov_result_metadatas: MetadataRepository
  RAW_pov_reports: MetadataRepository
  RAW_pov_report_representative_crashing_inputs: BlobRepository
  RAW_pov_report_representative_crashing_input_metadatas: MetadataRepository

  patch_diffs: BlobRepository
  patch_metadatas: MetadataRepository

imports:
  crs_utils:
    path: ../../components/common/base/crs-utils/pipeline.yaml
    repos:
      targets_with_sources: raw_targets_with_sources
      target_metadatas: target_metadatas
      target_harness_infos: harness_infos
      target_directed_fuzz_requests: target_directed_fuzz_requests
      info_extraction_requests: info_extraction_requests
      cp_image_ready: cp_image_ready
      all_non_kernel_targets_with_sources: all_non_kernel_targets_with_sources
      debug_built_targets_with_sources: debug_built_targets_with_sources
      crashing_harness_inputs: crashing_harness_inputs
      crashing_harness_inputs_metadatas: crashing_harness_inputs_metadatas
      crash_run_pov_result_metadatas: crash_run_pov_result_metadatas
      pov_reports: RAW_pov_reports
      pov_report_representative_crashing_inputs: RAW_pov_report_representative_crashing_inputs
      pov_report_representative_crashing_input_metadatas: RAW_pov_report_representative_crashing_input_metadatas

  time_saver:
    path: ../../components/common/TimeSaver/pipeline.yaml
    repos:
      targets_with_sources: targets_with_sources
      target_start_times: target_start_times

  svaultbard:
    path: ../../components/common/svaultbard/pipeline.yaml
    repos:
      targets_with_sources: targets_with_sources
      target_harness_infos: harness_infos
      target_directed_fuzz_requests: target_directed_fuzz_requests
      target_directed_seeds: target_directed_seeds

  antlr4_guy:
    path: ../../components/common/antlr4-guy/pipeline.yaml
    repos:
      targets_with_sources: java_targets_with_sources
      target_metadatas: target_metadatas
      commit_output_dir_java: commit_functions_jsons_dirs
      full_output_dir_java: full_functions_jsons_dirs

  clang_indexer:
    path: ../../components/common/clang-indexer/pipeline.yaml
    repos:
      c_targets_with_sources: c_targets_with_sources
      non_kernel_c_targets_with_sources: non_kernel_c_targets_with_sources
      target_metadatas: target_metadatas
      full_json_output_dirs: full_functions_jsons_dirs
      by_commit_json_output_dirs: commit_functions_jsons_dirs
  
  grammar_guy:
    path: ../../components/common/grammar-guy/pipeline.yaml
    repos:
      fuzz_requests: target_directed_fuzz_requests
      info_extraction_requests: info_extraction_requests
      targets_with_sources: all_non_kernel_targets_with_sources
      cp_image_ready: cp_image_ready
      target_harness_infos: harness_infos
      full_functions_indices: full_functions_indices
      full_functions_jsons_dirs: full_functions_jsons_dirs


  function_indexer:
    path: ../../components/common/function_index_generator/pipeline.yaml
    repos:
      commit_functions_indices: commit_functions_indices
      commit_functions_index_csvs: commit_functions_index_csvs
      commit_functions_jsons_dirs: commit_functions_jsons_dirs

      full_functions_jsons_dirs: full_functions_jsons_dirs
      full_functions_indices: full_functions_indices
      full_functions_index_csvs: full_functions_index_csvs

      full_functions_by_file_index_jsons: full_functions_by_file_index_jsons

      info_extraction_requests: info_extraction_requests

  codeql:
    path: ../../components/common/codeql/pipeline.yaml
    repos:
      target_metadatas: target_metadatas
      targets_with_sources: all_non_kernel_targets_with_sources
      cp_image_ready: cp_image_ready
      codeql_reports: codeql_reports
      codeql_qlpack_reports: codeql_qlpack_reports
      info_extraction_requests: info_extraction_requests
      info_extraction_results: info_extraction_results
      info_extraction_bqrs_results_dirs: codeql_targets_strings
      kernel_reachability_results: kernel_reachability_results
      libfuzzer_reaching_functions_dicts: libfuzzer_reaching_functions_dicts
      libfuzzer_reaching_files_dicts: libfuzzer_reaching_files_dicts

  pushpull:
    path: ../../components/common/docker-pushpull/pipeline.yaml
    repos:
      targets_with_sources: targets_with_sources
      cp_image_ready: cp_image_ready
