{{- range $i := until (.Values.global.num_concurrent_tasks.value | int) }}
{{- $taskid := add $i 1 }}
{{- with $ }}
---
{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "analysisgraph.fullname" . }}-{{ .Values.persistence.name }}-{{ $taskid }}
  labels:
    {{- include "analysisgraph.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "analysisgraph.name" . }}-{{ $taskid }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }} 
{{- end }} 
{{- end }} 