repo_classes:
  targets_with_sources: FilesystemRepository
  target_metadatas: MetadataRepository
  cp_image_ready: MetadataRepository
  debug_built_targets_with_sources: FilesystemRepository

  clang_indexer_meta_csvs: BlobRepository
  full_functions_indices: BlobRepository
  full_functions_jsons_dirs: FilesystemRepository
  full_functions_by_commit_jsons_dirs: FilesystemRepository
  full_functions_by_file_index_jsons: BlobRepository
  commit_functions_indices: BlobRepository
  commit_functions_index_csvs: BlobRepository
  commit_functions_jsons_dirs: FilesystemRepository

  target_harness_infos: MetadataRepository

  benign_harness_inputs: BlobRepository
  benign_harness_inputs_metadatas: MetadataRepository
  crashing_harness_inputs: BlobRepository
  crashing_harness_inputs_metadatas: MetadataRepository

  target_directed_fuzz_requests: MetadataRepository
  target_directed_fuzz_requests_seeds: FilesystemRepository

  codeql_reports: BlobRepository
  codeql_qlpack_reports: BlobRepository

  info_extraction_requests: MetadataRepository
  info_extraction_results: MetadataRepository
  kernel_reachability_results: MetadataRepository
  libfuzzer_reaching_functions_dicts: BlobRepository
  libfuzzer_reaching_files_dicts: BlobRepository

  crash_run_pov_result_metadatas: MetadataRepository
  pov_reports: MetadataRepository
  pov_report_representative_crashing_inputs: BlobRepository
  pov_report_representative_crashing_input_metadatas: MetadataRepository

  patch_diffs: BlobRepository
  patch_metadatas: MetadataRepository


imports:
  crs_utils:
    path: ../../../../common/base/crs-utils/pipeline.yaml
    repos:
      cp_image_ready: cp_image_ready
      targets_with_sources: targets_with_sources
      target_metadatas: target_metadatas
      target_harness_infos: target_harness_infos
      target_directed_fuzz_requests: target_directed_fuzz_requests
      debug_built_targets_with_sources: debug_built_targets_with_sources
      info_extraction_requests: info_extraction_requests

      crash_run_pov_result_metadatas: crash_run_pov_result_metadatas
      crashing_harness_inputs: crashing_harness_inputs
      crashing_harness_inputs_metadatas: crashing_harness_inputs_metadatas
      pov_reports: pov_reports
      pov_report_representative_crashing_inputs: pov_report_representative_crashing_inputs
      pov_report_representative_crashing_input_metadatas: pov_report_representative_crashing_input_metadatas
      patch_diffs: patch_diffs
      patch_metadatas: patch_metadatas
  # svaultbard:
  #   path: ../../../../common/svaultbard/pipeline.yaml
  #   repos:
  #     targets_with_sources: targets_with_sources
  #     target_directed_fuzz_requests: target_directed_fuzz_requests
  #     target_harness_infos: target_harness_infos
  #     target_directed_seeds: target_directed_fuzz_requests_seeds

  # clang_indexer:
  #   path: ../../../../common/clang-indexer/pipeline.yaml
  #   repos:
  #     c_targets_with_sources: targets_with_sources
  #     target_metadatas: target_metadatas
  #     full_json_output_dirs: full_functions_jsons_dirs
  #     by_commit_json_output_dirs: commit_functions_jsons_dirs

  # function_index_generator:
  #   path: ../../../../common/function_index_generator/pipeline.yaml
  #   repos:
  #     full_functions_jsons_dirs: full_functions_jsons_dirs
  #     full_functions_index_csvs: clang_indexer_meta_csvs
  #     full_functions_indices: full_functions_indices
  #     full_functions_by_file_index_jsons: full_functions_by_file_index_jsons
  #     commit_functions_jsons_dirs: commit_functions_jsons_dirs
  #     commit_functions_index_csvs: commit_functions_index_csvs
  #     commit_functions_indices: commit_functions_indices
  #     target_reachability_requests: target_reachability_requests

  # codeql:
  #   path: ../../../../common/codeql/pipeline.yaml
  #   repos:
  #     targets_with_sources: targets_with_sources
  #     target_metadatas: target_metadatas
  #     info_extraction_requests: target_reachability_requests
  #     codeql_reports: codeql_reports
  #     codeql_qlpack_reports: codeql_qlpack_reports
  #     info_extraction_results: info_extraction_results
  #     kernel_reachability_results: kernel_reachability_results
  #     libfuzzer_reaching_functions_dicts: libfuzzer_reaching_functions_dicts
  #     libfuzzer_reaching_files_dicts: libfuzzer_reaching_files_dicts

  aflpp:
    path: ../../pipeline-patch.yaml
    repos:
      targets_with_sources: targets_with_sources
      target_harness_infos: target_harness_infos
      patch_diffs: patch_diffs
      patch_metadatas: patch_metadatas
      pov_report_representative_crashing_input_metadatas: pov_report_representative_crashing_input_metadatas

      
      crashing_harness_inputs: crashing_harness_inputs
      crashing_harness_inputs_metadatas: crashing_harness_inputs_metadatas
      benign_harness_inputs: benign_harness_inputs
      benign_harness_inputs_metas: benign_harness_inputs_metadatas


