# Base image should always be the OSS FUZZ base image
ARG BASE_IMAGE=""
FROM ${BASE_IMAGE} 

RUN apt-get update && apt-get install -y valgrind zip gdbserver net-tools gdb

# Installing GDB 12, re https://github.com/google/oss-fuzz/issues/7513.
# RUN apt-get install -y build-essential libgmp-dev && \
#     wget https://ftp.gnu.org/gnu/gdb/gdb-12.1.tar.xz && \
#     tar -xf gdb-12.1.tar.xz && cd gdb-12.1 && ./configure &&  \
#     make -j $(expr $(nproc) / 2) && make install && cd .. && \
#     rm -rf gdb-12.1* && apt-get remove --purge -y build-essential libgmp-dev