from enum import Enum


class EVENTS(Enum):
    ### Generic Events ###
    LOG_EVENT = "LOG"
    COMPONENT_START = "START"
    COMPONENT_FINISH = "FINISH"
    COMPONENT_PENDING = "PENDING"
    COMPONENT_ERROR = "ERROR"
    DIFF_MODE = "DIFF"
    FULL_MODE = "FULL"
    SARIF_BROADCAST = "SARIF_BROADCAST"
    LLM_COST = "LLM COST"

    ### Clang Indexer Events ###
    CLANG_MODE = "CLANG_MODE"
    CLANG_FILE_COUNT = "CLANG_FILE_COUNT"
    CLANG_COMMIT_COUNT = "CLANG_COMMIT_COUNT"
    CLANG_FUNCTION_COUNT = "CLANG_FUNCTION_COUNT"
    CLANG_MACRO_COUNT = "CLANG_MACRO_COUNT"

    ### Function Indexer Events ###
    FUNCTION_INDEXER_MODE = "FUNCTION_INDEXER_MODE"
    FUNCTION_INDICES_COUNT = "FUNCTION_INDICES_COUNT"


class CLANG_INDEXER_MODES(Enum):
    FULL = "FULL"
    COMMIT = "COMMIT"


class FUNCTION_INDEXER_MODES(Enum):
    FULL = "FULL"
    COMMIT = "COMMIT"


class POIGUY_EVENTS(Enum):
    STACK_TRACES = "STACK_TRACES"
    POIS = "POIS"
    CRASH = "CRASH"


class PATCHERY_EVENTS(Enum):
    PROGRAM_POI = "PROGRAM POI"
    PATCHES = "PATCHES"


class AFLPP_EVENTS(Enum):
    STRATEGY = "STRATEGY"
    STATS = "STATS"
    BACKGROUND = "BACKGROUND"
    EDGES_FOUND = "EDGES_FOUND"
    TOTAL_EDGES = "TOTAL_EDGES"
    LAST_FIND = "LAST_FIND"
    LAST_CRASH = "LAST_CRASH"
    SAVED_CRASHES = "SAVED_CRASHES"
    EXECS_PER_SEC = "EXECS_PER_SEC"
    EXECS_PER_MIN = "EXECS_PER_MIN"
    CORPUS_COUNT = "CORPUS_COUNT"
    CORPUS_FAVORED = "CORPUS_FAVORED"
    CORPUS_FOUND = "CORPUS_FOUND"
    CORPUS_IMPORTED = "CORPUS_IMPORTED"
    CORPUS_VARIABLE = "CORPUS_VARIABLE"
    STABILITY = "STABILITY"
    BITMAP_CVG = "BITMAP_CVG"


class SUBMITTER_EVENTS(Enum):
    VDS = "VDS"
    PATCH = "PATCH"
    WAITING = "WAITING"
    SUCCESS = "SUCCESS"
    FAILURE = "FAILURE"
