name: "competitor-test-server"

x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "2"
    tag: "{{.Name}}|{{.ImageName}}|{{.ID}}"

include:
  - ./signoz/compose.yaml

services:
  dind:
    image: ${EXTERNAL_REGISTRY:-docker.io}/docker:28-dind
    command:
      [
        "dockerd",
        "-H",
        "tcp://0.0.0.0:2375",
        "--tls=false",
        "--storage-driver=overlay2",
      ]
    restart: always
    privileged: true
    network_mode: bridge
    expose:
      - "2375"
    environment:
      - DOCKER_TLS_CERTDIR= # Ensure this is correctly formatted (empty value)
      - DOCKER_DEFAULT_PLATFORM=linux/amd64
    volumes:
      - shared-tmp:/tmp

  scantron:
    image: ${EXTERNAL_REGISTRY:-ghcr.io/shellphish-support-syndicate}/competition-test-api:v1.1-rc4  
    platform: linux/amd64
    container_name: aixcc-competition-server
    privileged: true
    network_mode: bridge
    volumes:
      - ./scantron.yaml:/etc/scantron/scantron.yaml
      - shared-tmp:/tmp
    depends_on:
      - dind
    links:
      - dind
    command: server
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - "DOCKER_HOST=tcp://dind:2375"
      - DOCKER_DEFAULT_PLATFORM=linux/amd64
    logging: *logging

  port-forwarder:
    image: ${EXTERNAL_REGISTRY:-ghcr.io}/competition-server/port-forwarder:latest
    build:
      context: .
      dockerfile: Dockerfile.socat
    container_name: signoz-port-forwarder
    network_mode: host
    environment:
      - DOCKER_HOST=${DOCKER_HOST:-}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3301:3301
      - 4317:4317
      - 1323:1323
    restart: unless-stopped
    depends_on:
      - frontend
      - otel-collector
      - scantron
 


volumes:
  shared-tmp:
